insert into CATEGORIES values(1,'소고기');
insert into CATEGORIES values(2,'돼지고기');
insert into CATEGORIES values(3,'양고기');

(select MAX(NVL(INDEXNUMBER,0))+1 from ASSET_ACTIVITY)

SELECT * FROM ASSET_ACTIVITY;

SELECT INDEXNUMBER,ID,AMOUNT,CONTENTS,FIXED,A_DATE,A_TYPE,CATEGORY_NAME FROM ASSET_ACTIVITY A,CATEGORIES C WHERE A.CATEGORY_NUM=C.CATEGORY_NUM;

SELECT INDEXNUMBER,ID,A.CATEGORY_NUM AS CATEGORY_NUM,CONTENTS,AMOUNT,FIXED,A_DATE,A_TYPE,CATEGORY_NAME FROM ASSET_ACTIVITY A,CATEGORIES C WHERE A.CATEGORY_NUM=C.CATEGORY_NUM;