select id from users;
select * from users;

select id from users where id='qwq713'

INSERT INTO USERS (ID,PW,AGE,GENDER,JOB,POINT) VALUES ('java01','1234',66,'kk','kk',0)
INSERT INTO USERS (ID,PW,AGE,GENDER,JOB,POINT) VALUES ('java02','1234',66,'kk','kk',0)
INSERT INTO USERS (ID,PW,AGE,GENDER,JOB,POINT) VALUES ('java03','1234',66,'kk','kk',0)


SELECT INDEXNUMBER,ID,CATEGORY_NUM,CONTENTS,AMOUNT,FIXED,A_DATE,A_TYPE,CATEGORY_NAME 
FROM(SELECT INDEXNUMBER,ID,A.CATEGORY_NUM, CONTENTS,AMOUNT,FIXED,A_DATE,A_TYPE,CATEGORY_NAME
FROM ASSET_ACTIVITY A,CATEGORIES C WHERE A.CATEGORY_NUM=C.CATEGORY_NUM)